# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "debian/jessie64"

	config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
	config.vm.provision "shell", path: "install.sh", privileged: true

	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
	end
end

